using System.ComponentModel.DataAnnotations;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer:IValidatableObject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Transactions = new HashSet<Transaction>();
        }
         
        public decimal customerID { get; set; }
        
        public string name { get; set; }
        [MaxLength(25)]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string email { get; set; } 
        public decimal mobile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
             
            if (Transactions.Count == 5)
            {
                yield return new ValidationResult("Only 5 transaction allowed");
            }
        }
    }
}
