//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public decimal id { get; set; }
        public Nullable<decimal> customerID { get; set; }
        public System.DateTime date { get; set; }
        public decimal amount { get; set; }
        public string currency { get; set; }
        public string status { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
